/**
 * Canonical license-token contract + pipeline isolation.
 * Never prints tokens or secrets.
 */
const { describe, it, before, after, beforeEach, afterEach } = require('node:test');
const assert = require('node:assert/strict');

const SIGNING = 'canonical-license-signing-secret-abcdefghijklmnopqrstuvwxyz';

describe('LicenseTokenService canonical contract', () => {
  let previousEnv;
  let LicenseTokenService;
  let generateForUser;
  let verifyTradingViewWebhook;
  let PipelineStatusService;
  let PipelineDeliveryStatsService;

  before(() => {
    previousEnv = {
      NODE_ENV: process.env.NODE_ENV,
      WEBHOOK_SIGNING_SECRET: process.env.WEBHOOK_SIGNING_SECRET,
      TRADINGVIEW_WEBHOOK_SECRET: process.env.TRADINGVIEW_WEBHOOK_SECRET,
      LICENSE_TOKEN_TEST_ONLY: process.env.LICENSE_TOKEN_TEST_ONLY,
      ALLOW_LEGACY_WEBHOOK_SECRET: process.env.ALLOW_LEGACY_WEBHOOK_SECRET
    };
    process.env.WEBHOOK_SIGNING_SECRET = SIGNING;
    delete process.env.TRADINGVIEW_WEBHOOK_SECRET;
    delete process.env.ALLOW_LEGACY_WEBHOOK_SECRET;
    delete process.env.LICENSE_TOKEN_TEST_ONLY;
    LicenseTokenService = require('../LicenseTokenService');
    ({ generateForUser } = require('../PineScriptGeneratorService'));
    ({ verifyTradingViewWebhook } = require('../../utils/webhookSecurity'));
    PipelineStatusService = require('../PipelineStatusService');
    PipelineDeliveryStatsService = require('../PipelineDeliveryStatsService');
  });

  after(() => {
    for (const [key, value] of Object.entries(previousEnv)) {
      if (value === undefined) delete process.env[key];
      else process.env[key] = value;
    }
  });

  function reqWithBody(body) {
    return { body, headers: {}, rawBody: Buffer.from(JSON.stringify(body), 'utf8') };
  }

  function activeUser(id, tvu) {
    return {
      _id: id,
      tradingviewUsername: tvu,
      subscription: { status: 'active', tier: 'professional' }
    };
  }

  it('A. production token generated by canonical service verifies successfully', () => {
    const prev = process.env.NODE_ENV;
    process.env.NODE_ENV = 'production';
    try {
      const token = LicenseTokenService.generateLicenseToken(
        '64b0f0f0f0f0f0f0f0f0aa10',
        'prodtrader'
      );
      assert.match(token, /^kls_v2\./);
      const verified = LicenseTokenService.verifyLicenseTokenDetailed(token);
      assert.equal(verified.ok, true);
      assert.equal(verified.claims.env, 'production');
      assert.equal(verified.claims.uid, '64b0f0f0f0f0f0f0f0f0aa10');
      assert.equal(verified.claims.tvu, 'prodtrader');
      assert.equal(verified.claims.v, 2);
      assert.doesNotMatch(JSON.stringify(verified.claims), /WEBHOOK_SIGNING_SECRET|secret/i);
    } finally {
      process.env.NODE_ENV = prev;
    }
  });

  it('B. generated production Pine token verifies successfully', () => {
    const prev = process.env.NODE_ENV;
    process.env.NODE_ENV = 'production';
    try {
      const generated = generateForUser(
        {
          _id: '64b0f0f0f0f0f0f0f0f0aa11',
          email: 'prod-pine@example.com',
          tradingviewUsername: 'prodpine',
          subscription: { tier: 'professional', status: 'active' }
        },
        { webhookUrl: 'https://api.kachingscanner.com/api/webhook/tradingview', strategy: 'scalping' }
      );
      const verified = LicenseTokenService.verifyLicenseTokenDetailed(generated.licenseToken);
      assert.equal(verified.ok, true);
      assert.equal(verified.claims.env, 'production');
      assert.equal(verified.claims.uid, '64b0f0f0f0f0f0f0f0f0aa11');
      assert.equal(verified.claims.scriptGenerationId, generated.scriptGenerationId);
      assert.match(generated.script, /^LICENSE_TOKEN = str\.trim\("/m);
      assert.doesNotMatch(generated.script, /localhost|127\.0\.0\.1|smoke-optiona|smoke-test-license/);
      assert.doesNotMatch(generated.script, /kls_v1/);
      assert.match(generated.licenseToken, /^kls_v2\./);
    } finally {
      process.env.NODE_ENV = prev;
    }
  });

  it('C. development token is rejected by production', () => {
    process.env.LICENSE_TOKEN_TEST_ONLY = 'true';
    const prev = process.env.NODE_ENV;
    process.env.NODE_ENV = 'development';
    const token = LicenseTokenService.generateLicenseToken(
      '64b0f0f0f0f0f0f0f0f0aa12',
      'devtrader',
      { env: 'development', allowNonProduction: true }
    );
    process.env.NODE_ENV = 'production';
    try {
      const verified = LicenseTokenService.verifyLicenseTokenDetailed(token);
      assert.equal(verified.ok, false);
      assert.equal(verified.reason, 'non_production_license_token');
      assert.equal(verified.diagnostics.tokenEnvironment, 'development');
    } finally {
      process.env.NODE_ENV = prev;
      delete process.env.LICENSE_TOKEN_TEST_ONLY;
    }
  });

  it('D. test token is rejected by production', () => {
    const prev = process.env.NODE_ENV;
    process.env.NODE_ENV = 'test';
    const token = LicenseTokenService.generateLicenseToken('64b0f0f0f0f0f0f0f0f0aa13', 'testtrader');
    process.env.NODE_ENV = 'production';
    try {
      const verified = LicenseTokenService.verifyLicenseTokenDetailed(token);
      assert.equal(verified.ok, false);
      assert.equal(verified.reason, 'non_production_license_token');
      assert.equal(verified.diagnostics.tokenEnvironment, 'test');
    } finally {
      process.env.NODE_ENV = prev;
    }
  });

  it('E. smoke/local token is rejected by production with a clear reason', () => {
    const prev = process.env.NODE_ENV;
    process.env.NODE_ENV = 'test';
    const token = LicenseTokenService.generateLicenseToken('smoke-optiona-local', 'smoke_optiona_tv');
    process.env.NODE_ENV = 'production';
    try {
      const verified = LicenseTokenService.verifyLicenseTokenDetailed(token);
      assert.equal(verified.ok, false);
      assert.equal(verified.reason, 'non_production_license_token');
    } finally {
      process.env.NODE_ENV = prev;
    }
  });

  it('F. tampered token is rejected', () => {
    const prev = process.env.NODE_ENV;
    process.env.NODE_ENV = 'production';
    try {
      const token = LicenseTokenService.generateLicenseToken('64b0f0f0f0f0f0f0f0f0aa14', 'tampertrader');
      const parts = token.split('.');
      const tampered = `${parts[0]}.${parts[1]}.${parts[2]}x`;
      const verified = LicenseTokenService.verifyLicenseTokenDetailed(tampered);
      assert.equal(verified.ok, false);
      assert.equal(verified.reason, 'invalid_license_token');
    } finally {
      process.env.NODE_ENV = prev;
    }
  });

  it('G. missing token is rejected', async () => {
    const prev = process.env.NODE_ENV;
    process.env.NODE_ENV = 'production';
    try {
      const absent = LicenseTokenService.verifyLicenseTokenDetailed('');
      assert.equal(absent.ok, false);
      assert.equal(absent.reason, 'licenseToken_absent');
      const auth = await verifyTradingViewWebhook(
        reqWithBody({ symbol: 'XAUUSD', alertType: 'entry', tradingviewUsername: 'x' }),
        async () => null
      );
      assert.equal(auth.ok, false);
      assert.ok(['unauthorized', 'licenseToken_absent'].includes(auth.reason));
    } finally {
      process.env.NODE_ENV = prev;
    }
  });

  it('H. wrong user token produces license_user_mismatch only after signature validity', async () => {
    const prev = process.env.NODE_ENV;
    process.env.NODE_ENV = 'production';
    try {
      const userA = '64b0f0f0f0f0f0f0f0f0bb01';
      const userB = '64b0f0f0f0f0f0f0f0f0bb02';
      const tvu = 'sharedtv';
      const token = LicenseTokenService.generateLicenseToken(userA, tvu);
      assert.equal(LicenseTokenService.verifyLicenseTokenDetailed(token).ok, true);
      const auth = await verifyTradingViewWebhook(
        reqWithBody({
          symbol: 'XAUUSD',
          alertType: 'entry',
          userId: userB,
          tradingviewUsername: tvu,
          licenseToken: token
        }),
        async id => activeUser(id, tvu)
      );
      assert.equal(auth.ok, false);
      assert.equal(auth.reason, 'license_user_mismatch');
    } finally {
      process.env.NODE_ENV = prev;
    }
  });

  it('I. wrong TradingView username produces license_tv_username_mismatch only after signature validity', async () => {
    const prev = process.env.NODE_ENV;
    process.env.NODE_ENV = 'production';
    try {
      const userId = '64b0f0f0f0f0f0f0f0f0cc01';
      const token = LicenseTokenService.generateLicenseToken(userId, 'licensedtv');
      assert.equal(LicenseTokenService.verifyLicenseTokenDetailed(token).ok, true);
      const auth = await verifyTradingViewWebhook(
        reqWithBody({
          symbol: 'XAUUSD',
          alertType: 'entry',
          userId,
          tradingviewUsername: 'othertv',
          licenseToken: token
        }),
        async () => activeUser(userId, 'licensedtv')
      );
      assert.equal(auth.ok, false);
      assert.equal(auth.reason, 'license_tv_username_mismatch');
    } finally {
      process.env.NODE_ENV = prev;
    }
  });

  it('J. startup in-memory crypto check does not create Signal, Redis, Telegram, Email, or MT5', () => {
    const prev = process.env.NODE_ENV;
    process.env.NODE_ENV = 'production';
    LicenseTokenService.resetCryptoSelfCheckForTests();
    PipelineStatusService.resetForTests();
    const created = [];
    const Signal = require('../../models/Signal');
    const origCreate = Signal.create;
    const origSave = Signal.prototype.save;
    Signal.create = async function mockedCreate(...args) {
      created.push(args);
      return origCreate?.apply?.(this, args);
    };
    Signal.prototype.save = async function mockedSave(...args) {
      created.push(['save', this]);
      return origSave?.apply?.(this, args);
    };
    try {
      const check = LicenseTokenService.runCryptoSelfCheck();
      assert.equal(check.ok, true);
      assert.equal(check.isolated, true);
      assert.equal(check.tokenEnvironment, 'production');
      assert.equal(created.length, 0);
      assert.equal(PipelineStatusService.getLiveEvents(10).length, 0);
      assert.equal(LicenseTokenService.getCryptoSelfCheckResult().ok, true);
    } finally {
      Signal.create = origCreate;
      Signal.prototype.save = origSave;
      process.env.NODE_ENV = prev;
    }
  });

  it('K/L. real auth creates one persist path; auth failure creates zero Signal and no delivery', async () => {
    const prev = process.env.NODE_ENV;
    process.env.NODE_ENV = 'production';
    const userId = '64b0f0f0f0f0f0f0f0f0dd01';
    const tvu = 'persisttv';
    const token = LicenseTokenService.generateLicenseToken(userId, tvu);
    const auth = await verifyTradingViewWebhook(
      reqWithBody({
        symbol: 'EURUSD',
        alertType: 'entry',
        userId,
        tradingviewUsername: tvu,
        licenseToken: token
      }),
      async () => activeUser(userId, tvu)
    );
    assert.equal(auth.ok, true);

    const failed = await verifyTradingViewWebhook(
      reqWithBody({
        symbol: 'EURUSD',
        alertType: 'entry',
        userId,
        tradingviewUsername: tvu,
        licenseToken: 'kls_v2.not-real.not-real'
      }),
      async () => activeUser(userId, tvu)
    );
    assert.equal(failed.ok, false);
    assert.equal(failed.reason, 'invalid_license_token');
    process.env.NODE_ENV = prev;
  });

  it('legacy kls_v1 production token still verifies when HMAC matches and env is absent', () => {
    const prev = process.env.NODE_ENV;
    process.env.NODE_ENV = 'production';
    try {
      const payload = {
        uid: '64b0f0f0f0f0f0f0f0f0ee01',
        tvu: 'legacytv',
        v: 2,
        iat: Math.floor(Date.now() / 1000)
      };
      const encoded = Buffer.from(JSON.stringify(payload)).toString('base64url');
      const signature = require('crypto')
        .createHmac('sha256', SIGNING)
        .update(encoded)
        .digest('base64url');
      const legacy = `kls_v1.${encoded}.${signature}`;
      const verified = LicenseTokenService.verifyLicenseTokenDetailed(legacy);
      assert.equal(verified.ok, true);
      assert.equal(verified.claims.uid, payload.uid);

      const withCR = `${legacy}\r`;
      const crOk = LicenseTokenService.verifyLicenseTokenDetailed(withCR);
      assert.equal(crOk.ok, true, 'kls_v1 with trailing CR (transport artifact) must verify');
      assert.equal(crOk.diagnostics.hasCR, true);
      assert.equal(crOk.claims.uid, payload.uid);
    } finally {
      process.env.NODE_ENV = prev;
    }
  });

  it('kls_v2 with outer CR/LF/whitespace verifies; tampered and non-production reject', () => {
    const prev = process.env.NODE_ENV;
    process.env.NODE_ENV = 'production';
    try {
      const token = LicenseTokenService.generateLicenseToken(
        '64b0f0f0f0f0f0f0f0f0aa11',
        'crtrader'
      );
      const padded = `\r\n  ${token}  \r`;
      const ok = LicenseTokenService.verifyLicenseTokenDetailed(padded);
      assert.equal(ok.ok, true);
      assert.equal(ok.claims.tvu, 'crtrader');

      const tampered = `${token.slice(0, -2)}xx`;
      const bad = LicenseTokenService.verifyLicenseTokenDetailed(tampered);
      assert.equal(bad.ok, false);
      assert.equal(bad.reason, 'invalid_license_token');

      const devPayload = {
        v: 2,
        env: 'development',
        uid: '64b0f0f0f0f0f0f0f0f0aa11',
        tvu: 'crtrader',
        iat: Math.floor(Date.now() / 1000),
        issuer: 'kaching-license'
      };
      const encoded = Buffer.from(JSON.stringify(devPayload)).toString('base64url');
      const signature = require('crypto')
        .createHmac('sha256', SIGNING)
        .update(encoded)
        .digest('base64url');
      const nonProd = `kls_v2.${encoded}.${signature}`;
      const rejected = LicenseTokenService.verifyLicenseTokenDetailed(nonProd);
      assert.equal(rejected.ok, false);
      assert.equal(rejected.reason, 'non_production_license_token');
    } finally {
      process.env.NODE_ENV = prev;
    }
  });

  it('production mint refuses smoke users and localhost webhook URLs', () => {
    const prev = process.env.NODE_ENV;
    process.env.NODE_ENV = 'production';
    try {
      assert.throws(
        () =>
          LicenseTokenService.generateLicenseToken('smoke-optiona-local', 'smoke_optiona_tv'),
        /smoke\/dev identity/
      );
      assert.throws(
        () =>
          generateForUser(
            {
              _id: '64b0f0f0f0f0f0f0f0f0ff01',
              email: 'local@example.com',
              tradingviewUsername: 'localtv',
              subscription: { tier: 'professional', status: 'active' }
            },
            { webhookUrl: 'http://localhost:4000/api/webhook/tradingview' }
          ),
        /localhost webhook/
      );
    } finally {
      process.env.NODE_ENV = prev;
    }
  });
});

describe('Admin counters remain Mongo-backed and ignore auth failures', () => {
  const Signal = require('../../models/Signal');
  const mongoose = require('mongoose');
  let PipelineDeliveryStatsService;
  let readyDesc;
  let origAggregate;
  let origCount;

  beforeEach(() => {
    delete require.cache[require.resolve('../PipelineDeliveryStatsService')];
    PipelineDeliveryStatsService = require('../PipelineDeliveryStatsService');
    readyDesc = Object.getOwnPropertyDescriptor(mongoose.connection, 'readyState');
    Object.defineProperty(mongoose.connection, 'readyState', {
      configurable: true,
      get: () => 1
    });
    origAggregate = Signal.aggregate;
    origCount = Signal.countDocuments;
  });

  afterEach(() => {
    Signal.aggregate = origAggregate;
    Signal.countDocuments = origCount;
    if (readyDesc) Object.defineProperty(mongoose.connection, 'readyState', readyDesc);
    delete require.cache[require.resolve('../PipelineDeliveryStatsService')];
  });

  it('K. durable Signal count increments Signals today from Mongo only', async () => {
    Signal.aggregate = async () => [{ n: 1 }];
    Signal.countDocuments = async () => 0;
    const stats = await PipelineDeliveryStatsService.computeDeliveryStatistics();
    assert.equal(stats.signalsToday, 1);
  });

  it('L. auth failure does not increment Signals today', async () => {
    const DurableDelivery = require('../../utils/durableDelivery');
    DurableDelivery.resetForTests();
    Signal.aggregate = async () => [];
    Signal.countDocuments = async () => 0;
    const stats = await PipelineDeliveryStatsService.computeDeliveryStatistics();
    assert.equal(stats.signalsToday, 0);
    assert.equal(stats.telegramSuccessPct, null);
  });

  it('M/N. Telegram success uses attempted denominator; zero attempts stay —', async () => {
    const DurableDelivery = require('../../utils/durableDelivery');
    DurableDelivery.resetForTests();
    Signal.aggregate = async () => [{ n: 2 }];
    Signal.countDocuments = async () => 0;
    await DurableDelivery.ensureJob({
      eventId: 'e1',
      canonicalTradeId: 't1',
      subscriberId: 'sub1',
      channel: 'telegram',
      eventType: 'entry'
    });
    const delivered = await DurableDelivery.commitDeliveredBySpec(
      {
        eventId: 'e1',
        canonicalTradeId: 't1',
        subscriberId: 'sub1',
        channel: 'telegram',
        eventType: 'entry'
      },
      { reason: 'test' }
    );
    assert.equal(delivered.status, 'delivered');
    const stats = await PipelineDeliveryStatsService.computeDeliveryStatistics();
    assert.equal(stats.telegramSuccessPct, 100);
    DurableDelivery.resetForTests();
  });

  it('O. MT5 success stays — when no MT5 attempts', async () => {
    Signal.aggregate = async () => [{ n: 3 }];
    Signal.countDocuments = async filter => {
      if (filter?.$or?.some(part => part.mt5Sent === true || part.executionChannel)) return 0;
      return 0;
    };
    const stats = await PipelineDeliveryStatsService.computeDeliveryStatistics();
    assert.equal(stats.mt5SuccessPct, null);
  });
});

describe('P. self-test isolation from production Admin counters', () => {
  const PipelineStatusService = require('../PipelineStatusService');
  const { percent } = require('../../utils/pipelineObservability');

  it('self-test telemetry is marked non-production and excluded from durable Mongo save', () => {
    PipelineStatusService.resetForTests();
    PipelineStatusService.record('WebhookReceived', 'PASS', {
      symbol: 'STEST1',
      signalUuid: 'selftest_abc',
      selfTest: true
    });
    PipelineStatusService.record('MongoSave', 'PASS', {
      symbol: 'STEST1',
      signalUuid: 'selftest_abc',
      selfTest: true,
      reason: 'Success; in_memory_fallback; id=mem_1'
    });
    assert.equal(
      PipelineStatusService.isNonProductionPipelineTelemetry({
        symbol: 'STEST1',
        signalUuid: 'selftest_abc',
        selfTest: true
      }),
      true
    );
    assert.equal(
      PipelineStatusService.isDurableMongoSaveStamp({
        symbol: 'STEST1',
        selfTest: true,
        reason: 'Success; in_memory_fallback'
      }),
      false
    );
    assert.equal(percent(0, 0), null);
  });
});
